### PR TITLE
Cast integer key to str if str key exist in dictionary

### PR DESCRIPTION
**Pull request by jferreira-ca**
Fix for issue where we have a numeric key in dictionary that is a string, and dpath.util.new creates the same numeric key but as an integer.

Actual Result:
```
a = {"root": {"1": {"k": "v"}}}
dpath.util.new(a, "root/1/k", "new")

Out[6]: {'root': {'1': {'k': 'v'}, 1: {'k': 'new'}}}
```

Expected Result:
```
a = {"root": {"1": {"k": "v"}}}
dpath.util.new(a, "root/1/k", "new")

Out[6]: {'root': {'1': {'k': 'new'}}
```

### CODE REVIEW

**Comment by jferreira-ca** [comment]
thanks @moomoohk.

**Comment by moomoohk** [comment]
I've gone over your change and I'm not sure this patch is needed.

While debugging the `set` function I discovered that the `segments` variable is set to: `['root', 1, 'k']` where you're obviously expecting it to be: `['root', '1', 'k']`.

So I checked and the `segments` variable is created in the `new` function by calling the `__safe_path__` function (`util.py:62`).

In the `__safe_path__` function you'll find the path parser which also contains code to convert `int`-like segments to `int` objects. Your suggested patch ultimately undoes that action.

Instead of doing that, you could set `dpath.options.CONVERT_INT_LIKE_SEGMENTS` to `False`. This will disable the conversion code in the path parser.

Please let me know if this proposal solves your issue.

**Comment by jferreira-ca** [comment]
It worked. Thanks for you support on that. I think we can close this PR then.

**Comment by jferreira-ca** [comment]
sorry about that. I'm reopening it. The option works well if we are not using lists. But for our scenario we're using nested dicts and lists all together, on this case if we use that option it'll cause a TypeError.

Example:
imagine I want to set a new value for the fist element on the list: `{"list": [{"root": {"1": {"k": None}}}]}`
like: `dpath.util.new(a, "list/0/root/1/z", "new")`

actual:
TypeError: list indices must be integers or slices, not str

expected:
`{"list": [{"root": {"1": {"k": None, "z": "new"}}}]}`

**Comment by moomoohk** [comment]
I believe that problem can be overcome by using a custom creator function and passing it using the `creator` kwarg.

Please refer to [this](https://github.com/dpath-maintainers/dpath-python/issues/160#issuecomment-1027259408) comment  (the code there doesn't work in your specific case).

**Comment by moomoohk** [comment]
Hi @jferreira-ca,
I'm currently working on a major refactor to this project. Among other changes I've better documented the creator feature.
In case you'd like to have a look, here is the relevant code on the refactor branch: https://github.com/dpath-maintainers/dpath-python/blob/feature/refactor/dpath/types.py#L29

**Comment by jferreira-ca** [comment]
Hey @moomoohk thanks for the response. Before open this PR we actually tested passing a new creator function, but for this scenario specifically it does not work.

**Comment by moomoohk** [comment]
Could you please include some example code? (The creator that failed)

**Comment by jferreira-ca** [comment]
Even passing a creator the code still breaks cause segments.set function still tries to access the node using the int key.

**Comment by moomoohk** [comment]
@jferreira-ca I've pushed a small change to the branch `bugfix/bad-type-check`. Please try passing your creator on that branch and let me know if it works.

**Comment by jferreira-ca** [comment]
Honestly I don't understand how a creator could help on this case. The problem happens when a dict has ant int key on it as str (e.g `"1": {}`. Note is not `1: {}`)

**Comment by moomoohk** [comment]
@jferreira-ca I've identified the issue. Please follow #169 for updates.

I'm closing this PR.

Regards.

**Comment by jferreira-ca** [comment]
thanks!!!

**Pull request closed without merging**
